# Generated by Django 3.1.3 on 2020-11-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201115_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileprice',
            name='telecom_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telecomcompany', verbose_name='Telecom Company'),
        ),
    ]
