# Generated by Django 3.1.3 on 2020-11-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201115_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Country Name')),
                ('telecom_company', models.ManyToManyField(to='core.TelecomCompany')),
            ],
        ),
    ]
