# Generated by Django 3.1.3 on 2020-11-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_country'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('name', 'mobile')},
        ),
    ]
