# Generated by Django 3.1.3 on 2020-11-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201115_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name'),
        ),
    ]
