# Generated by Django 3.1.3 on 2020-11-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mobile_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileprice',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='mobileprice',
            name='mobile_variations',
        ),
        migrations.RemoveField(
            model_name='mobileprice',
            name='package',
        ),
        migrations.RemoveField(
            model_name='mobileprice',
            name='telecom_company',
        ),
        migrations.RemoveField(
            model_name='mobiletechnicalspecification',
            name='mobile',
        ),
        migrations.AlterUniqueTogether(
            name='mobilevariation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mobilevariation',
            name='variation',
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='package',
            name='telecom_company',
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variation',
            name='mobile',
        ),
        migrations.DeleteModel(
            name='MobileCameraSpecification',
        ),
        migrations.DeleteModel(
            name='MobilePrice',
        ),
        migrations.DeleteModel(
            name='MobileTechnicalSpecification',
        ),
        migrations.DeleteModel(
            name='MobileVariation',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
