# Generated by Django 3.1.3 on 2020-11-23 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecompanies', '0006_auto_20201123_0232'),
        ('core', '0009_auto_20201122_2220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobile',
        ),
        migrations.DeleteModel(
            name='MobileBrand',
        ),
    ]
