# Generated by Django 3.1.3 on 2020-11-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_mobile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name')),
                ('cash_price', models.FloatField(blank=True, null=True, verbose_name='Cash Price')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mobiles/', verbose_name='Image')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mobilebrand', to='core.mobilebrand', verbose_name='Brand')),
            ],
        ),
    ]
