# Generated by Django 3.1.3 on 2020-11-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_mobile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.AlterField(
            model_name='mobile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobile')),
            ],
            options={
                'unique_together': {('name', 'mobile')},
            },
        ),
        migrations.CreateModel(
            name='MobileTechnicalSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_g', models.BooleanField()),
                ('three_g', models.BooleanField()),
                ('four_g', models.BooleanField()),
                ('five_g', models.BooleanField()),
                ('WiFi', models.BooleanField()),
                ('taleVoLTE', models.BooleanField()),
                ('dual_sim', models.BooleanField()),
                ('dimensions', models.CharField(max_length=50, verbose_name='dimensions')),
                ('weight', models.CharField(max_length=10, verbose_name='weight')),
                ('screen_type', models.CharField(max_length=50, verbose_name='screen_type')),
                ('screen_size', models.CharField(max_length=10, verbose_name='screen_size')),
                ('screen_resolution', models.CharField(max_length=30, verbose_name='screen_resolution')),
                ('ip_certification', models.CharField(max_length=10, verbose_name='ip_certification')),
                ('internal_storage', models.CharField(max_length=10, verbose_name='internal_storage')),
                ('external_storage', models.CharField(max_length=10, verbose_name='external_storage')),
                ('WLAN', models.CharField(max_length=10, verbose_name='WLAN')),
                ('bluetooth', models.CharField(max_length=30, verbose_name='bluetooth')),
                ('NFC', models.BooleanField(default=True)),
                ('USB', models.CharField(max_length=10, verbose_name='USB')),
                ('wireless_charging', models.CharField(max_length=30, verbose_name='wireless_charging')),
                ('fast_charging', models.CharField(max_length=30, verbose_name='fast_charging')),
                ('chipset', models.CharField(max_length=30, verbose_name='chipset')),
                ('control_system', models.CharField(max_length=30, verbose_name='control_system')),
                ('ram', models.CharField(blank=True, max_length=10, null=True, verbose_name='RAM')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='MobileCameraSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rear_cam_lenses', models.IntegerField(verbose_name='rear_camera_lenses')),
                ('rear_cam_megapixel', models.CharField(max_length=30, verbose_name='rear_camera_megapixel')),
                ('back_cam_aperture', models.CharField(max_length=30, verbose_name='Rear Camera Aperture')),
                ('rear_cam_video_resolution', models.CharField(max_length=30, verbose_name='rear_camera_video_resolution')),
                ('front_cam_lenses', models.IntegerField(verbose_name='front_camera_lenses')),
                ('front_cam_megapixel', models.CharField(max_length=30, verbose_name='front_camera_megapixel')),
                ('front_cam_aperture', models.CharField(max_length=30, verbose_name='front_camera_aperture')),
                ('front_cam_video_resolution', models.CharField(max_length=30, verbose_name='front_camera_video_resolution')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobile')),
            ],
        ),
        migrations.AlterField(
            model_name='mobile',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Mobilebrand', to='mobiles.mobilebrand', verbose_name='Brand'),
        ),
        migrations.CreateModel(
            name='MobileVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='value')),
                ('variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobiles.variation')),
            ],
            options={
                'unique_together': {('variation', 'value')},
            },
        ),
    ]
