# Generated by Django 3.1.3 on 2020-11-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_auto_20201122_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobiles', to='mobiles.mobilebrand', verbose_name='Brand'),
        ),
    ]
