# Generated by Django 3.1.3 on 2020-11-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0005_auto_20201123_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='USB',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='USB'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='WLAN',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WLAN'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='WiFi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='chipset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='chipset'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='control_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Control System'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='dual_sim',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='external_storage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='External Storage'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='fast_charging',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fast Charging'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='five_g',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='four_g',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Internal Storage'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='ip_certification',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP Certification'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='ram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Screen Resolution'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='screen_size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Screen Size'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='screen_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Screen Type'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='taleVoLTE',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='three_g',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='two_g',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='wireless_charging',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Wireless Charging'),
        ),
    ]
