# Generated by Django 3.1.3 on 2020-11-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_auto_20201124_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiletechnicalspecification',
            name='taleVoLTE',
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='chipset',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chipset'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Weight'),
        ),
    ]
