# Generated by Django 3.1.3 on 2020-11-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0007_auto_20201125_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='NFC',
            field=models.BooleanField(default=False),
        ),
    ]
