# Generated by Django 3.1.3 on 2020-11-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0008_auto_20201125_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiletechnicalspecification',
            name='control_system',
        ),
        migrations.AddField(
            model_name='mobiletechnicalspecification',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operating System'),
        ),
    ]
