# Generated by Django 3.1.3 on 2020-11-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0009_auto_20201125_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='front_cam_megapixel',
            field=models.CharField(max_length=60, verbose_name='front_camera_megapixel'),
        ),
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='rear_cam_megapixel',
            field=models.CharField(max_length=60, verbose_name='rear_camera_megapixel'),
        ),
    ]
