# Generated by Django 3.1.3 on 2020-11-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0011_auto_20201125_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='front_cam_lenses',
            field=models.IntegerField(blank=True, null=True, verbose_name='front_camera_lenses'),
        ),
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='rear_cam_lenses',
            field=models.IntegerField(blank=True, null=True, verbose_name='rear_camera_lenses'),
        ),
    ]
