# Generated by Django 3.1.3 on 2020-11-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0013_auto_20201125_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='back_cam_aperture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rear Camera Aperture'),
        ),
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='front_cam_aperture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='front_camera_aperture'),
        ),
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='front_cam_video_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='front_camera_video_resolution'),
        ),
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='rear_cam_video_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='rear_camera_video_resolution'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='USB',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='USB'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='WLAN',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='WLAN'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='chipset',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chipset'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='dimensions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='external_storage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External Storage'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='fast_charging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fast Charging'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='internal_storage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Internal Storage'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='ip_certification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IP Certification'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='operating_system',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='ram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Resolution'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='screen_size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Size'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='screen_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Screen Type'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='weight',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='wireless_charging',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wireless Charging'),
        ),
        migrations.AlterField(
            model_name='mobilevariation',
            name='value',
            field=models.CharField(max_length=255, verbose_name='value'),
        ),
    ]
