# Generated by Django 3.1.3 on 2020-11-30 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0014_auto_20201130_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecameraspecification',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_specs', to='mobiles.mobile'),
        ),
        migrations.AlterField(
            model_name='mobiletechnicalspecification',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specs', to='mobiles.mobile'),
        ),
    ]
