# Generated by Django 3.1.3 on 2020-11-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0015_auto_20201130_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiletechnicalspecification',
            name='battery_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Battery Type'),
        ),
        migrations.AddField(
            model_name='mobiletechnicalspecification',
            name='launch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Launch'),
        ),
    ]
