# Generated by Django 3.1.3 on 2020-12-04 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0016_auto_20201130_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularMobile',
            fields=[
                ('mobile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mobiles.mobile')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
        ),
    ]
