# Generated by Django 3.1.3 on 2020-12-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0017_popularmobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mobile_brands/', verbose_name='Image'),
        ),
    ]
