# Generated by Django 3.1.3 on 2020-11-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecompanies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Discount'),
        ),
    ]
