# Generated by Django 3.1.3 on 2020-11-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201115_2123'),
        ('telecompanies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mobile', verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Price'),
        ),
    ]
