# Generated by Django 3.1.3 on 2020-11-19 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telecompanies', '0002_auto_20201117_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='updated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Updated'),
            preserve_default=False,
        ),
    ]
