# Generated by Django 3.1.3 on 2020-11-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecompanies', '0004_auto_20201120_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='discount_offered',
            field=models.FloatField(blank=True, null=True, verbose_name='Discount Offered'),
        ),
    ]
