# Generated by Django 3.1.3 on 2020-11-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_auto_20201123_0232'),
        ('telecompanies', '0005_offer_discount_offered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobiles.mobile', verbose_name='Mobile'),
        ),
    ]
