# Generated by Django 3.1.3 on 2020-11-24 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0005_auto_20201123_1654'),
        ('telecompanies', '0006_auto_20201123_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobiles.mobile', verbose_name='Mobile'),
        ),
    ]
