# Generated by Django 3.1.3 on 2020-12-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecompanies', '0007_auto_20201124_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_url',
            field=models.URLField(blank=True, null=True, verbose_name='Offer Url'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Price'),
        ),
    ]
