# Generated by Django 3.1.3 on 2020-12-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0020_mobiletechnicalspecification_status'),
        ('telecompanies', '0008_auto_20201208_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='mobile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='mobiles.mobile', verbose_name='Mobile'),
        ),
    ]
