name: Django CI

on:
  push:
    branches: [ main, pv0 ]
  pull_request:
    branches: [ main, pv0 ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env: 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        # DATABASES:
        #   #default:
        test:
          # engine: ${{ secrets.DB_ENGINE }}
          - NAME: ${{ secrets.DB_NAME }}
          # user: ${{ secrets.DB_USER }}
          # password: ${{ secrets.DB_PASSWORD }}
          # host: ${{ secrets.DB_HOST }}
          # port: ${{ secrets.DB_PORT }}

      run: python manage.py test
